config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/team'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :commom_content, :only => [:index, :team]


  def commom_content
    @hero_name = Faker::Superhero.name
    @hero_power = Faker::Superhero.power
    @hero_corp_power = Faker::Company.bs
    @hero_corp_title = Faker::Job.title
    @hero_corp_title = @hero_corp_title.titleize
    
    @rand_avatar = rand(1..1000)
    @rand_set = "set" + rand(1..4).to_s
    @rand_bg = "bg" + rand(1..2).to_s
    
    @avatar = Faker::Avatar.image(slug: @rand_avatar , size: "300x300", format: "png", set: @rand_set, bgset: @rand_bg)
  end

  def index
  end

  def team
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SUPERHERO NAME GENERATOR', root_path, class:'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to 'Home Page', root_path %> </li> 
		<li><%= link_to 'Create a Team', home_team_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    	<%= link_to 'Click Here To Generate A New Superhero', root_path %>
	</h3>
  </div>
  <div class="panel-body">
    <%= @avatar %>
    <br/>
    <br/>
    <br/>
    Name: <%= @hero_name %>
    <br/>
    Power: <%= @hero_power %>
    <br/>
    Day Job: <%= @hero_corp_title %>
    <br/>
    Corp Power: <%= @hero_corp_power %>
  </div>
  <div class="panel-footer">
  	<%= link_to 'Create A Whole Superhero Team', home_team_path %>
  </div>
</div>

app/views/home/team.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    	<%= link_to 'Click Here To Generate A New Superhero', root_path %>
	</h3>
  </div>
  <div class="panel-body">
    Panel content
  </div>
  <div class="panel-footer">
  	<%= link_to 'Create A Whole Superhero Team', home_team_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <%= yield %>
    <div class="container">

      <br/><br/><br/><br/><br/>
      <center>Copyright</center>
  </body>
</html>